### ISSUE TITLE
global name 'response' is not defined

### ISSUE THREAD

**Issue by brishtiteveja** [orisi/orisi#92]
I was trying to follow the tutorial from https://github.com/orisi/wiki/wiki/Performing-a-Timelock-transaction.

After running the ./runoracle.sh successfully.... I am getting following error:
-------------------------------------------------------------------------------------------------------------

./runclient.sh main
number of nodes: 3
required signatures: 2

Traceback (most recent call last):
  File "/orisi/src/client/main.py", line 458, in <module>
    main(args)
  File "/orisi/src/client/main.py", line 450, in main
    operation(args[1:])
  File "/orisi/src/client/main.py", line 113, in main
    print "1. wire the funds to %s" % response['address']
NameError: global name 'response' is not defined

------------------------------------------------------------------------------------------------------------
Successful runoracle.sh output:
/orisi# ./runoracle.sh
 ./runoracle.sh: line 6: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
running oracle
2015-06-04 14:52:11,420 [INFO    ] fastcast pubkey: u'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC77PxcpRBECTdNeKESFHBoPQKlcGyAdcz5rBN3B8AfqcpYK5zlNGG4ZpQFszlkRlxliqfjOz13xU3Q42rjbV9LPFzQqTa06SokMdnytBkjpJcsWh0je2q2RJTxPWznpLneDQ+ACSXeLa+tZco6mR0gQCp3NmJqlJ037ENIbSzT7QIDAQAB'
2015-06-04 14:52:11,420 [INFO    ] my fee: 1e-05
2015-06-04 14:52:11,421 [INFO    ] my bitcoin address is 17j2ZRJVP29HMnNJYyjQvjWcZrdLknJKJr
2015-06-04 14:52:11,500 [INFO    ] my bitcoin pubkey: '0368a3d3b91630216a4b80cfaceb8cbd20956662811f45ae9625a04c3389e6aa8b'

**Comment by kolinko** [comment]
That's weird. You might want to add:

  response = btc.create_multisig_address(min_sigs, oracle_pubkeys)

In the line 110 of client/main.py

Keep in mind though that the project is on pause for a few years now, and the oracles are shut down. I can try answering some support requests that you have, but it might take you a while to understand what's going on here.

(thanks for the pull request btw, if you keep them coming, I'll keep accepting them and can give you admin rights even)

**Comment by syclops** [comment]
I found this issue and tried the fix, but I still get the following error:

```
number of nodes: 3
required signatures: 2
Traceback (most recent call last):
  File "/home/vagrant/orisi/src/client/main.py", line 458, in <module>
    main(args)
  File "/home/vagrant/orisi/src/client/main.py", line 450, in main
    operation(args[1:])
  File "/home/vagrant/orisi/src/client/main.py", line 110, in main
    response = btc.create_multisig_address(min_sigs, oracle_pubkeys)
NameError: global name 'btc' is not defined
```

From other locations in the code, it seems you should also add

```
btc = BitcoinClient()
```

but to do this we also need to add the following near the beginning of the file:

  from shared.bitcoind_client.bitcoinclient import BitcoinClient

But now running `./runclient.sh main` just hangs. What's going on here?
